const oFilaMint = {
    CodeName: "oFilaMint",
    EngName: "Fila-mint",
    SunNum: 0,
    Attack: "Heavy",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Boost",
    Usage: "Single, Instant",
    Family: "Fila-mint",
};
const oPepperMint = {
    CodeName: "oPepperMint",
    EngName: "Pepper-mint",
    SunNum: 0,
    Attack: "Heavy",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Fire Trail, Boost",
    Usage: "Single, Instant",
    Family: "Pepper-mint",
};
const oWinterMint = {
    CodeName: "oWinterMint",
    EngName: "Winter-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Chill, Boost",
    Usage: "Single, Instant",
    Family: "Winter-mint",
};
const oEnlightenMint = {
    CodeName: "oEnlightenMint",
    EngName: "Enlighten-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Boost",
    Usage: "Single, Instant, Sun (Normal)",
    Family: "Enlighten-mint",
};
const oReinforceMint = {
    CodeName: "oReinforceMint",
    EngName: "Reinforce-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Knockback, Boost",
    Usage: "Single, Instant",
    Family: "Reinforce-mint",
};
const oBombardMint = {
    CodeName: "oBombardMint",
    EngName: "Bombard-mint",
    SunNum: 0,
    Attack: "Massive",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Boost",
    Usage: "Single, Instant",
    Family: "Bombard-mint",
};
const oAilMint = {
    CodeName: "oAilMint",
    EngName: "Ail-mint",
    SunNum: 0,
    Attack: "Moderate",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Poison, Boost",
    Usage: "Single, Instant",
    Family: "Ail-mint",
};
const oEnchantMint = {
    CodeName: "oEnchantMint",
    EngName: "Enchant-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Hypnotize Zombie, Boost",
    Usage: "Single, Instant",
    Family: "Enchant-mint",
};
const oContainMint = {
    CodeName: "oContainMint",
    EngName: "Contain-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Stun, Boost",
    Usage: "Single, Instant",
    Family: "Contain-mint",
};
const oEnforceMint = {
    CodeName: "oEnforceMint",
    EngName: "Enforce-mint",
    SunNum: 0,
    Attack: null,
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Weaken Zombie, Boost",
    Usage: "Single, Instant",
    Family: "Enforce-mint",
};
const oArmaMint = {
    CodeName: "oArmaMint",
    EngName: "Arma-mint",
    SunNum: 0,
    Attack: "Massive",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Stun, Boost",
    Usage: "Single, Instant",
    Family: "Arma-mint",
};
const oConcealMint = {
    CodeName: "oConcealMint",
    EngName: "Conceal-mint",
    SunNum: 0,
    Attack: "Huge",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Zombies Dragged, Boost",
    Usage: "Single, Instant",
    Family: "Conceal-mint",
};
const oSpearMint = {
    CodeName: "oSpearMint",
    EngName: "Spear-mint",
    SunNum: 0,
    Attack: "Normal",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Column 9, Full Board",
    Special: "Spawn Spikerocks, Boost",
    Usage: "Single, Instant",
    Family: "Spear-mint",
};
const oAppeaseMint = {
    CodeName: "oAppeaseMint",
    EngName: "Appease-mint",
    SunNum: 0,
    Attack: "Extensive",
    World: "Power Mints",
    Recharge: "Very Slow",
    RangeArea: "Straight, Full Board",
    Special: "Boost",
    Usage: "Single, Instant",
    Family: "Appease-mint",
};