const oTorchwood = {
    CodeName: "oTorchwood",
    EngName: "Torchwood",
    SunNum: 175,
    Attack: "Extensive",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Lane",
    Special: "Boost Projectiles",
    Usage: "Wall (Elevated), On Eaten",
    Family: "Appease-mint",
};
const oStarfruit = {
    CodeName: "oStarfruit",
    EngName: "Starfruit",
    SunNum: 150,
    Attack: "Normal",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "5 Way",
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oDandelion = {
    CodeName: "oDandelion",
    EngName: "Dandelion",
    SunNum: 275,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Multi-Lane (3 Lanes)",
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oBloomingHeart = {
    CodeName: "oBloomingHeart",
    EngName: "Blooming Heart",
    SunNum: 150,
    Attack: "Variable",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Lobbed",
    Special: "Stackable Damage",
    Usage: null,
    Family: "Ail-mint",
};
const oExplodeONut = {
    CodeName: "oExplodeONut",
    EngName: "Explode-O-Nut",
    SunNum: 150,
    Attack: "Massive",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "3x3",
    Special: null,
    Usage: "Wall (High), On Eaten",
    Family: "Bombard-mint",
};
const oAloe = {
    CodeName: "oAloe",
    EngName: "Aloe",
    SunNum: 75,
    Attack: null,
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Close",
    Special: "Heal Plant",
    Usage: null,
    Family: "Reinforce-mint",
};
const oBombegranate = {
    CodeName: "oBombegranate",
    EngName: "Bombegranate",
    SunNum: 150,
    Attack: "Massive",
    World: "Seedium",
    Recharge: "Slow",
    RangeArea: "3x3",
    Special: "Seed Damage",
    Usage: null,
    Family: "Bombard-mint",
};
const oHotDate = {
    CodeName: "oHotDate",
    EngName: "Hot Date",
    SunNum: 175,
    Attack: "Huge",
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Multi-Lane (3 Lanes)",
    Special: null,
    Usage: "Wall (Elevated), On Death",
    Family: "Pepper-mint",
};
const oSolarTomato = {
    CodeName: "oSolarTomato",
    EngName: "Solar Tomato",
    SunNum: 100,
    Attack: null,
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "3x3",
    Special: "Stun",
    Usage: "Sun (Variable), Single, Instant",
    Family: "Enlighten-mint",
};
const oShadowPeashooter = {
    CodeName: "oShadowPeashooter",
    EngName: "Shadow Peashooter",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Multi-Hit, Straight Ahead",
    Special: "Zombies Dragged, Stall",
    Usage: null,
    Family: "Conceal-mint",
};
const oGooPeashooter = {
    CodeName: "oGooPeashooter",
    EngName: "Goo Peashooter",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Poison, Stall",
    Usage: null,
    Family: "Ail-mint",
};
const oSlingPea = {
    CodeName: "oSlingPea",
    EngName: "Sling Pea",
    SunNum: 125,
    Attack: "Normal",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Full Board",
    Special: null,
    Usage: null,
    Family: "Arma-mint",
};
const oSnapPea = {
    CodeName: "oSnapPea",
    EngName: "Snap Pea",
    SunNum: 200,
    Attack: "Extensive",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Straight Ahead",
    Special: "Chew Speed",
    Usage: null,
    Family: "Enforce-mint",
};
const oZoybeanPod = {
    CodeName: "oZoybeanPod",
    EngName: "Zoybean Pod",
    SunNum: 200,
    Attack: null,
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: null,
    Special: "Spawn Zomboids",
    Usage: null,
    Family: "Enchant-mint",
};
const oDazeyChain = {
    CodeName: "oDazeyChain",
    EngName: "Dazey Chain",
    SunNum: 150,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Multi-Hit, Straight Ahead",
    Special: "Stun, Growth",
    Usage: null,
    Family: "Contain-mint",
};
const oElectriciTea = {
    CodeName: "oElectriciTea",
    EngName: "Electrici-tea",
    SunNum: 125,
    Attack: "Huge",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Multi-Hit",
    Special: "Zombies Zapped",
    Usage: "On Eaten",
    Family: "Fila-mint",
};
const oBlastberryVine = {
    CodeName: "oBlastberryVine",
    EngName: "Blastberry Vine",
    SunNum: 175,
    Attack: "Normal",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Lobbed",
    Special: null,
    Usage: "Plant On Plants",
    Family: "Arma-mint",
};
const oPokra = {
    CodeName: "oPokra",
    EngName: "Pokra",
    SunNum: 175,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Close, Multi-Hit, Straight Ahead",
    Special: "Stall",
    Usage: null,
    Family: "Spear-mint",
};
const oImpPear = {
    CodeName: "oImpPear",
    EngName: "Imp Pear",
    SunNum: 0,
    Attack: null,
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Touch, Single",
    Special: "Transform Zombie",
    Usage: "On Eaten",
    Family: "Ail-mint",
};
const oPumpkin = {
    CodeName: "oPumpkin",
    EngName: "Pumpkin",
    SunNum: 150,
    Attack: null,
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: null,
    Special: null,
    Usage: "Wall (High), Plant On Plants",
    Family: "Reinforce-mint",
};
const oPyreVine = {
    CodeName: "oPyreVine",
    EngName: "Pyre Vine",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "2 Tiles Ahead",
    Special: "Warming",
    Usage: "Plant On Plants",
    Family: "Pepper-mint",
};
const oIceBloom = {
    CodeName: "oIceBloom",
    EngName: "Ice Bloom",
    SunNum: 200,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "3x3, Full Board",
    Special: "Freeze, Chill",
    Usage: "Single, Instant",
    Family: "Winter-mint",
};
const oDartichoke = {
    CodeName: "oDartichoke",
    EngName: "Dartichoke",
    SunNum: 225,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Straight",
    Special: "Target Priority, Critical Damage",
    Usage: null,
    Family: "Spear-mint",
};
const oUltomato = {
    CodeName: "oUltomato",
    EngName: "Ultomato",
    SunNum: 250,
    Attack: "Massive",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Straight",
    Special: "Varied Cost, Stackable",
    Usage: null,
    Family: "Fila-mint",
};
const oGumnut = {
    CodeName: "oGumnut",
    EngName: "Gumnut",
    SunNum: 125,
    Attack: null,
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Touch, Tile",
    Special: "Spawn Barrier",
    Usage: "Wall (Very High)",
    Family: "Reinforce-mint",
};
const oShineVine = {
    CodeName: "oShineVine",
    EngName: "Shine Vine",
    SunNum: 75,
    Attack: null,
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Touch",
    Special: "Stun, Boost Sun Production",
    Usage: "Sun (Normal), Plant On Plants",
    Family: "Enlighten-mint",
};
const oTumbleweed = {
    CodeName: "oTumbleweed",
    EngName: "Tumbleweed",
    SunNum: 50,
    Attack: "Light",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Multi-Hit",
    Special: "Knockback, Stun, Toss, Rush, Shot Bounces",
    Usage: "Single, Instant",
    Family: "Appease-mint",
};
const oOlivePit = {
    CodeName: "oOlivePit",
    EngName: "Olive Pit",
    SunNum: 175,
    Attack: null,
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Tile, 3 Tiles Ahead",
    Special: "Zombies Dragged, Chew Speed, Weaken Zombie",
    Usage: null,
    Family: "Contain-mint",
};
const oPuffball = {
    CodeName: "oPuffball",
    EngName: "Puffball",
    SunNum: 150,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "3 Columns",
    Special: "Poison, Stun",
    Usage: "Single, Instant",
    Family: "Ail-mint",
};
const oExplodeOVine = {
    CodeName: "oExplodeOVine",
    EngName: "Explode-o-Vine",
    SunNum: 150,
    Attack: "Massive",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "3x3",
    Special: "Knockback",
    Usage: "Plant On Plants, Instant, On Eaten",
    Family: "Bombard-mint",
};
const oMurkadamiaNut = {
    CodeName: "oMurkadamiaNut",
    EngName: "Murkadamia Nut",
    SunNum: 100,
    Attack: null,
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Touch",
    Special: "Spawn Barrier, Regeneration, Mirror Damage",
    Usage: "Wall (High)",
    Family: "Conceal-mint",
};
const oTurkeyPult = {
    CodeName: "oTurkeyPult",
    EngName: "Turkey-pult",
    SunNum: 150,
    Attack: "Light",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: "Spawn Tofu Turkeys",
    Usage: null,
    Family: "Arma-mint",
};
const oHeadbutterLettuce = {
    CodeName: "oHeadbutterLettuce",
    EngName: "Headbutter Lettuce",
    SunNum: 175,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Close (Front & Back)",
    Special: "Stun",
    Usage: "Wall (Firm)",
    Family: "Enforce-mint",
};
const oBoingsetta = {
    CodeName: "oBoingsetta",
    EngName: "Boingsetta",
    SunNum: 175,
    Attack: "Huge",
    World: "Seedium",
    Recharge: "Slow",
    RangeArea: "Full Board, Lane",
    Special: "Chill, Knockback, Arming Time (Slow)",
    Usage: "Instant",
    Family: "Winter-mint",
};
const oStickybombRice = {
    CodeName: "oStickybombRice",
    EngName: "Stickybomb Rice",
    SunNum: 225,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Lobbed (Front & Back), Multi-Lane (3 Lanes)",
    Special: "Stackable Damage",
    Usage: null,
    Family: "Arma-mint",
};
const oHocusCrocus = {
    CodeName: "oHocusCrocus",
    EngName: "Hocus Crocus",
    SunNum: 225,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Full Board",
    Special: "Teleport Zombie, Firing Rate (Slow)",
    Usage: null,
    Family: "Enchant-mint",
};
const oGloomVine = {
    CodeName: "oGloomVine",
    EngName: "Gloom Vine",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "3x3",
    Special: "Boost",
    Usage: null,
    Family: "Conceal-mint",
};
const oDraftodil = {
    CodeName: "oDraftodil",
    EngName: "Draftodil",
    SunNum: 100,
    Attack: "Light",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Straight Ahead",
    Special: "Stall, Stun, Toss",
    Usage: null,
    Family: "Contain-mint",
};
const oBoomBalloonFlower = {
    CodeName: "oBoomBalloonFlower",
    EngName: "Boom Balloon Flower",
    SunNum: 350,
    Attack: "Huge",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Full Board",
    Special: "Firing Rate (Mediocre), Spawn Traps",
    Usage: "Tap to Aim",
    Family: "Bombard-mint",
};
const oPeaVine = {
    CodeName: "oPeaVine",
    EngName: "Pea Vine",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Boost",
    Usage: "Plant On Plants",
    Family: "Appease-mint",
};
const oInferno = {
    CodeName: "oInferno",
    EngName: "Inferno",
    SunNum: 200,
    Attack: "Normal",
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Multi-Hit, Straight Ahead",
    Special: "Knockback, Warming",
    Usage: null,
    Family: "Pepper-mint",
};
const oSolarSage = {
    CodeName: "oSolarSage",
    EngName: "Solar Sage",
    SunNum: 0,
    Attack: null,
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Touch",
    Special: "Transform Zombie, Flying",
    Usage: "Sun (Variable), Single, On Contact",
    Family: "Enlighten-mint",
};
const oPowerVine = {
    CodeName: "oPowerVine",
    EngName: "Power Vine",
    SunNum: 150,
    Attack: "Light",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Boost Power Vines",
    Usage: "Plant On Plants",
    Family: "Fila-mint",
};
const oNoctarine = {
    CodeName: "oNoctarine",
    EngName: "Noctarine",
    SunNum: 150,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "3x3",
    Special: "Boost, Stall",
    Usage: "Single, Instant",
    Family: "Conceal-mint",
};
const oHeathSeeker = {
    CodeName: "oHeathSeeker",
    EngName: "Heath Seeker",
    SunNum: 125,
    Attack: "Huge",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Full Board",
    Special: null,
    Usage: "Single, Instant",
    Family: "Spear-mint",
};
const oIceweed = {
    CodeName: "oIceweed",
    EngName: "Iceweed",
    SunNum: 150,
    Attack: "Light",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Tile",
    Special: "Chill",
    Usage: null,
    Family: "Winter-mint",
};
const oTigerGrass = {
    CodeName: "oTigerGrass",
    EngName: "Tiger Grass",
    SunNum: 150,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "4 Tiles Ahead",
    Special: "Spawn Grass Tiger, Regeneration, Growth",
    Usage: null,
    Family: "Enforce-mint",
};
const oTeleportatoMine = {
    CodeName: "oTeleportatoMine",
    EngName: "Teleportato Mine",
    SunNum: 150,
    Attack: "Massive",
    World: "Seedium",
    Recharge: "Sluggish",
    RangeArea: "Full Board, 3x3",
    Special: "Teleport Zombie, Arming Time (Mediocre)",
    Usage: "Single, Instant",
    Family: "Enforce-mint",
};
const oBlockoli = {
    CodeName: "oBlockoli",
    EngName: "Blockoli",
    SunNum: 150,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Close",
    Special: "Stun, Arming Time (Slow)",
    Usage: "Wall (Very High)",
    Family: "Reinforce-mint",
};
const oButtercup = {
    CodeName: "oButtercup",
    EngName: "Buttercup",
    SunNum: 25,
    Attack: "Heavy",
    World: "Seedium",
    Recharge: "Mediocre",
    RangeArea: "Close",
    Special: "Stun",
    Usage: "Wall (Firm)",
    Family: "Contain-mint",
};
const oBrambleBush = {
    CodeName: "oBrambleBush",
    EngName: "Bramble Bush",
    SunNum: 125,
    Attack: "Moderate",
    World: "Seedium",
    Recharge: "Fast",
    RangeArea: "Close",
    Special: "Stun",
    Usage: "Single",
    Family: "Spear-mint",
};