"use strict";
const oPeashooter = {
    CodeName: "oPeashooter",
    EngName: "Peashooter",
    SunNum: 100,
    Attack: "Normal",
    World: "Player's House",
    Recharge: "Fast",
    RangeArea: "Straight",
    SunProd: null,
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oSunflower = {
    CodeName: "oSunflower",
    EngName: "Sunflower",
    SunNum: 50,
    Attack: null,
    World: "Player's House",
    Recharge: "Fast",
    RangeArea: null,
    Special: null,
    Usage: "Sun (Normal)",
    Family: "Enlighten-mint",
};
const oWallNut = {
    CodeName: "oWallNut",
    EngName: "Wall-nut",
    SunNum: 50,
    Attack: null,
    World: "Player's House",
    Recharge: "Sluggish",
    RangeArea: null,
    Special: null,
    Usage: "Wall (High)",
    Family: "Reinforce-mint",
};
const oPotatoMine = {
    CodeName: "oPotatoMine",
    EngName: "Potato Mine",
    SunNum: 25,
    Attack: "Massive",
    World: "Player's House",
    Recharge: "Sluggish",
    RangeArea: "Tile",
    Special: "Arming Time (Slow)",
    Usage: null,
    Family: "Bombard-mint",
};
const oCabbagePult = {
    CodeName: "oCabbagePult",
    EngName: "Cabbage-pult",
    SunNum: 100,
    Attack: "Normal",
    World: "Player's House",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: null,
    Usage: null,
    Family: "Arma-mint",
};
const oBloomerang = {
    CodeName: "oBloomerang",
    EngName: "Bloomerang",
    SunNum: 175,
    Attack: "Normal",
    World: "Ancient Egypt",
    Recharge: "Fast",
    RangeArea: "Multi-Hit, Ahead",
    Special: null,
    Usage: null,
    Family: "Spear-mint",
};
const oIcebergLettuce = {
    CodeName: "oIcebergLettuce",
    EngName: "Iceberg Lettuce",
    SunNum: 0,
    Attack: null,
    World: "Ancient Egypt",
    Recharge: "Sluggish",
    RangeArea: "Touch, Single",
    Special: "Freeze",
    Usage: "Single, On Contact",
    Family: "Winter-mint",
};
const oGraveBuster = {
    CodeName: "oGraveBuster",
    EngName: "Grave Buster",
    SunNum: 0,
    Attack: null,
    World: "Ancient Egypt",
    Recharge: "Mediocre",
    RangeArea: null,
    Special: null,
    Usage: "On Gravestone",
    Family: "Contain-mint",
};
const oBonkChoy = {
    CodeName: "oBonkChoy",
    EngName: "Bonk Choy",
    SunNum: 150,
    Attack: "Heavy",
    World: "Ancient Egypt",
    Recharge: "Fast",
    RangeArea: "Close (Front & Back)",
    Special: null,
    Usage: null,
    Family: "Enforce-mint",
};
const oRepeater = {
    CodeName: "oRepeater",
    EngName: "Repeater",
    SunNum: 200,
    Attack: "Moderate",
    World: "Ancient Egypt",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oTwinSunflower = {
    CodeName: "oTwinSunflower",
    EngName: "Twin Sunflower",
    SunNum: 125,
    Attack: null,
    World: "Ancient Egypt",
    Recharge: "Mediocre",
    RangeArea: null,
    Special: null,
    Usage: "Sun (Double)",
    Family: "Enlighten-mint",
};
const oKernelPult = {
    CodeName: "oKernelPult",
    EngName: "Kernel-pult",
    SunNum: 100,
    Attack: "Light",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: "Stun",
    Usage: null,
    Family: "Arma-mint",
};
const oSnapdragon = {
    CodeName: "oSnapdragon",
    EngName: "Snapdragon",
    SunNum: 150,
    Attack: "Moderate",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "2x3",
    Special: "Warming",
    Usage: null,
    Family: "Pepper-mint",
};
const oSpikeweed = {
    CodeName: "oSpikeweed",
    EngName: "Spikeweed",
    SunNum: 100,
    Attack: "Light",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "Tile",
    Special: null,
    Usage: null,
    Family: "Spear-mint",
};
const oSpringBean = {
    CodeName: "oSpringBean",
    EngName: "Spring Bean",
    SunNum: 50,
    Attack: null,
    World: "Pirate Seas",
    Recharge: "Sluggish",
    RangeArea: "Touch, Single",
    Special: "Knockback, Recovery (Normal)",
    Usage: null,
    Family: "Contain-mint",
};
const oCoconutCannon = {
    CodeName: "oCoconutCannon",
    EngName: "Coconut Cannon",
    SunNum: 400,
    Attack: "Massive",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "3x3",
    Special: "Firing Rate (Slow)",
    Usage: "Tap to Use",
    Family: "Arma-mint",
};
const oThreepeater = {
    CodeName: "oThreepeater",
    EngName: "Threepeater",
    SunNum: 300,
    Attack: "Normal",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "Multi-Lane (3 Lanes)",
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oSpikerock = {
    CodeName: "oSpikerock",
    EngName: "Spikerock",
    SunNum: 250,
    Attack: "Normal",
    World: "Pirate Seas",
    Recharge: "Fast",
    RangeArea: "Tile",
    Special: null,
    Usage: null,
    Family: "Spear-mint",
};
const oCherryBomb = {
    CodeName: "oCherryBomb",
    EngName: "Cherry Bomb",
    SunNum: 150,
    Attack: "Massive",
    World: "Pirate Seas",
    Recharge: "Slow",
    RangeArea: "3x3",
    Special: null,
    Usage: "Single, Instant",
    Family: "Bombard-mint",
};
const oSplitPea = {
    CodeName: "oSplitPea",
    EngName: "Split Pea",
    SunNum: 125,
    Attack: "Moderate",
    World: "Wild West",
    Recharge: "Fast",
    RangeArea: "Straight (Front & Back)",
    Special: null,
    Usage: null,
    Family: "Appease-mint",
};
const oChiliBean = {
    CodeName: "oChiliBean",
    EngName: "Chili Bean",
    SunNum: 50,
    Attack: null,
    World: "Wild West",
    Recharge: "Sluggish",
    RangeArea: "Touch, Single, 2x1",
    Special: "Stun",
    Usage: "On Eaten",
    Family: "Ail-mint",
};
const oPeaPod = {
    CodeName: "oPeaPod",
    EngName: "Pea Pod",
    SunNum: 125,
    Attack: "Normal",
    World: "Wild West",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Stackable",
    Usage: null,
    Family: "Appease-mint",
};
const oLightningReed = {
    CodeName: "oLightningReed",
    EngName: "Lightning Reed",
    SunNum: 125,
    Attack: "Light",
    World: "Wild West",
    Recharge: "Fast",
    RangeArea: "Multi-Hit",
    Special: "Zombies Zapped",
    Usage: null,
    Family: "Fila-mint",
};
const oMelonPult = {
    CodeName: "oMelonPult",
    EngName: "Melon-pult",
    SunNum: 300,
    Attack: "Heavy",
    World: "Wild West",
    Recharge: "Fast",
    RangeArea: "Lobbed, 3x3",
    Special: null,
    Usage: null,
    Family: "Arma-mint",
};
const oTallNut = {
    CodeName: "oTallNut",
    EngName: "Tall-nut",
    SunNum: 125,
    Attack: null,
    World: "Wild West",
    Recharge: "Sluggish",
    RangeArea: null,
    Special: null,
    Usage: "Wall (Very High)",
    Family: "Reinforce-mint",
};
const oWinterMelon = {
    CodeName: "oWinterMelon",
    EngName: "Winter Melon",
    SunNum: 500,
    Attack: "Heavy",
    World: "Wild West",
    Recharge: "Fast",
    RangeArea: "Lobbed, 3x3",
    Special: "Chill",
    Usage: null,
    Family: "Winter-mint",
};
const oHotPotato = {
    CodeName: "oHotPotato",
    EngName: "Hot Potato",
    SunNum: 0,
    Attack: null,
    World: "Frostbite Caves",
    Recharge: "Mediocre",
    RangeArea: "Single",
    Special: null,
    Usage: "Single, Instant",
    Family: "Pepper-mint",
};
const oPepperPult = {
    CodeName: "oPepperPult",
    EngName: "Pepper-pult",
    SunNum: 200,
    Attack: "Moderate",
    World: "Frostbite Caves",
    Recharge: "Sluggish",
    RangeArea: "Lobbed",
    Special: "Warming",
    Usage: null,
    Family: "Pepper-mint",
};
const oChardGuard = {
    CodeName: "oChardGuard",
    EngName: "Chard Guard",
    SunNum: 75,
    Attack: "Moderate",
    World: "Frostbite Caves",
    Recharge: "Mediocre",
    RangeArea: null,
    Special: "Leaf Pushes",
    Usage: "Wall (Elevated)",
    Family: "Reinforce-mint",
};
const oStunion = {
    CodeName: "oStunion",
    EngName: "Stunion",
    SunNum: 25,
    Attack: null,
    World: "Frostbite Caves",
    Recharge: "Mediocre",
    RangeArea: "Close, 2x1",
    Special: "Stun",
    Usage: "Single, On Contact",
    Family: "Contain-mint",
};
const oRotobaga = {
    CodeName: "oRotobaga",
    EngName: "Rotobaga",
    SunNum: 150,
    Attack: "Normal",
    World: "Frostbite Caves",
    Recharge: "Fast",
    RangeArea: "4 Way",
    Special: "Flying",
    Usage: null,
    Family: "Appease-mint",
};
const oRedStinger = {
    CodeName: "oRedStinger",
    EngName: "Red Stinger",
    SunNum: 150,
    Attack: "Variable",
    World: "Lost City",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: null,
    Usage: "Wall (Variable)",
    Family: "Appease-mint",
};
const oAKEE = {
    CodeName: "oAKEE",
    EngName: "A.K.E.E.",
    SunNum: 175,
    Attack: "Normal",
    World: "Lost City",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: "Shot Bounces",
    Usage: null,
    Family: "Arma-mint",
};
const oEndurian = {
    CodeName: "oEndurian",
    EngName: "Endurian",
    SunNum: 100,
    Attack: "Normal",
    World: "Lost City",
    Recharge: "Mediocre",
    RangeArea: "Touch",
    Special: null,
    Usage: "Wall (Elevated)",
    Family: "Reinforce-mint",
};
const oStallia = {
    CodeName: "oStallia",
    EngName: "Stallia",
    SunNum: 0,
    Attack: null,
    World: "Lost City",
    Recharge: "Sluggish",
    RangeArea: "Touch, 3x3",
    Special: "Stall",
    Usage: "Single, On Contact",
    Family: "Contain-mint",
};
const oGoldLeaf = {
    CodeName: "oGoldLeaf",
    EngName: "Gold Leaf",
    SunNum: 80,
    Attack: null,
    World: "Lost City",
    Recharge: "Slow",
    RangeArea: "Tile",
    Special: null,
    Usage: "Single, Instant",
    Family: "Enlighten-mint",
};
const oLaserBean = {
    CodeName: "oLaserBean",
    EngName: "Laser Bean",
    SunNum: 200,
    Attack: "Moderate",
    World: "Far Future",
    Recharge: "Fast",
    RangeArea: "Multi-Hit, Ahead",
    Special: null,
    Usage: null,
    Family: "Spear-mint",
};
const oBlover = {
    CodeName: "oBlover",
    EngName: "Blover",
    SunNum: 50,
    Attack: null,
    World: "Far Future",
    Recharge: "Fast",
    RangeArea: "Full Board",
    Special: "Toss",
    Usage: "Single, Instant",
    Family: "Contain-mint",
};
const oCitron = {
    CodeName: "oCitron",
    EngName: "Citron",
    SunNum: 350,
    Attack: "Huge",
    World: "Far Future",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Firing Rate (Slow)",
    Usage: null,
    Family: "Fila-mint",
};
const oEMPeach = {
    CodeName: "oEMPeach",
    EngName: "E.M.Peach",
    SunNum: 25,
    Attack: null,
    World: "Far Future",
    Recharge: "Sluggish",
    RangeArea: "Radius",
    Special: "Stun",
    Usage: "Single, Instant",
    Family: "Fila-mint",
};
const oInfiNut = {
    CodeName: "oInfiNut",
    EngName: "Infi-nut",
    SunNum: 75,
    Attack: null,
    World: "Far Future",
    Recharge: "Sluggish",
    RangeArea: null,
    Special: "Regeneration",
    Usage: "Wall (Elevated)",
    Family: "Reinforce-mint",
};
const oMagnifyingGrass = {
    CodeName: "oMagnifyingGrass",
    EngName: "Magnifying Grass",
    SunNum: 50,
    Attack: "Huge",
    World: "Far Future",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: null,
    Usage: "Tap to Use",
    Family: "Fila-mint",
};
const oTileTurnip = {
    CodeName: "oTile Turnip",
    EngName: "Tile Turnip",
    SunNum: 250,
    Attack: null,
    World: "Far Future",
    Recharge: "Mediocre",
    RangeArea: "Tile",
    Special: "Varied Cost",
    Usage: "Single, Instant",
    Family: "Enchant-mint",
};
const oSunShroom = {
    CodeName: "oSunShroom",
    EngName: "Sun-shroom",
    SunNum: 25,
    Attack: null,
    World: "Dark Ages",
    Recharge: "Fast",
    RangeArea: null,
    Special: "Growth",
    Usage: "Sun (Variable)",
    Family: "Enlighten-mint",
};
const oPuffShroom = {
    CodeName: "oPuffShroom",
    EngName: "Puff-shroom",
    SunNum: 0,
    Attack: "Normal",
    World: "Dark Ages",
    Recharge: "Fast",
    RangeArea: "3 Tiles Ahead",
    Special: "Lifespan",
    Usage: null,
    Family: "Ail-mint",
};
const oFumeShroom = {
    CodeName: "oFumeShroom",
    EngName: "Fume-shroom",
    SunNum: 125,
    Attack: "Moderate",
    World: "Dark Ages",
    Recharge: "Fast",
    RangeArea: "4x1",
    Special: null,
    Usage: null,
    Family: "Ail-mint",
};
const oSunBean = {
    CodeName: "oSunBean",
    EngName: "Sun Bean",
    SunNum: 50,
    Attack: null,
    World: "Dark Ages",
    Recharge: "Sluggish",
    RangeArea: null,
    Special: null,
    Usage: "Single, On Eaten, Sun (Variable)",
    Family: "Enlighten-mint",
};
const oMagnetShroom = {
    CodeName: "oMagnetShroom",
    EngName: "Magnet-shroom",
    SunNum: 100,
    Attack: null,
    World: "Dark Ages",
    Recharge: "Mediocre",
    RangeArea: "Multi-Lane (5x7)",
    Special: "Destroy Objects",
    Usage: null,
    Family: "Contain-mint",
};
const oPhatBeet = {
    CodeName: "oPhatBeet",
    EngName: "Phat Beet",
    SunNum: 150,
    Attack: "Moderate",
    World: "Neon Mixtape Tour",
    Recharge: "Fast",
    RangeArea: "3x3",
    Special: "Critical Damage",
    Usage: null,
    Family: "Enforce-mint",
};
const oCeleryStalker = {
    CodeName: "oCeleryStalker",
    EngName: "Celery Stalker",
    SunNum: 50,
    Attack: "Huge",
    World: "Neon Mixtape Tour",
    Recharge: "Mediocre",
    RangeArea: "Close",
    Special: null,
    Usage: "Wall (Elevated)",
    Family: "Enforce-mint",
};
const oThymeWarp = {
    CodeName: "oThymeWarp",
    EngName: "Thyme Warp",
    SunNum: 100,
    Attack: null,
    World: "Neon Mixtape Tour",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Teleport Zombie",
    Usage: "Single, Instant",
    Family: "Contain-mint",
};
const oGarlic = {
    CodeName: "oGarlic",
    EngName: "Garlic",
    SunNum: 50,
    Attack: null,
    World: "Neon Mixtape Tour",
    Recharge: "Fast",
    RangeArea: "Touch",
    Special: null,
    Usage: "Single, Instant",
    Family: "Ail-mint",
};
const oSporeShroom = {
    CodeName: "oSporeShroom",
    EngName: "Spore-shroom",
    SunNum: 150,
    Attack: "Moderate",
    World: "Neon Mixtape Tour",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: "Duplication",
    Usage: null,
    Family: "Ail-mint",
};
const oIntensiveCarrot = {
    CodeName: "oIntensiveCarrot",
    EngName: "Intensive Carrot",
    SunNum: 100,
    Attack: null,
    World: "Neon Mixtape Tour",
    Recharge: "Sluggish",
    RangeArea: "Single",
    Special: "Restore Life",
    Usage: "Single, Instant",
    Family: "Enchant-mint",
};
const oPrimalPeashooter = {
    CodeName: "oPrimalPeashooter",
    EngName: "Primal Peashooter",
    SunNum: 175,
    Attack: "Normal",
    World: "Jurassic Marsh",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Knockback",
    Usage: null,
    Family: "Appease-mint",
};
const oPrimalWallNut = {
    CodeName: "oPrimalWallNut",
    EngName: "Primal Wall-nut",
    SunNum: 75,
    Attack: null,
    World: "Jurassic Marsh",
    Recharge: "Fast",
    RangeArea: null,
    Special: null,
    Usage: "Wall (High)",
    Family: "Reinforce-mint",
};
const oPerfumeShroom = {
    CodeName: "oPerfumeShroom",
    EngName: "Perfume-shroom",
    SunNum: 150,
    Attack: null,
    World: "Jurassic Marsh",
    Recharge: "Sluggish",
    RangeArea: "Lane",
    Special: null,
    Usage: "Single, Instant",
    Family: "Ail-mint",
};
const oPrimalSunflower = {
    CodeName: "oPrimalSunflower",
    EngName: "Primal Sunflower",
    SunNum: 75,
    Attack: null,
    World: "Jurassic Marsh",
    Recharge: "Fast",
    RangeArea: null,
    Special: null,
    Usage: "Sun (Large)",
    Family: "Enlighten-mint",
};
const oPrimalPotatoMine = {
    CodeName: "oPrimalPotatoMine",
    EngName: "Primal Potato Mine",
    SunNum: 50,
    Attack: "Massive",
    World: "Jurassic Marsh",
    Recharge: "Sluggish",
    RangeArea: "3x3",
    Special: "Arming Time (Mediocre)",
    Usage: null,
    Family: "Bombard-mint",
};
const oLilyPad = {
    CodeName: "oLilyPad",
    EngName: "Lily Pad",
    SunNum: 25,
    Attack: null,
    World: "Big Wave Beach",
    Recharge: "Fast",
    RangeArea: null,
    Special: "Amphibious",
    Usage: "Plant On Plants",
    Family: "Contain-mint",
};
const oTangleKelp = {
    CodeName: "oTangleKelp",
    EngName: "Tangle Kelp",
    SunNum: 25,
    Attack: "Huge",
    World: "Big Wave Beach",
    Recharge: "Sluggish",
    RangeArea: "Touch, Single",
    Special: "Zombies Dragged",
    Usage: "Single, On Contact",
    Family: "Enforce-mint",
};
const oBowlingBulb = {
    CodeName: "oBowlingBulb",
    EngName: "Bowling Bulb",
    SunNum: 200,
    Attack: "Heavy",
    World: "Big Wave Beach",
    Recharge: "Fast",
    RangeArea: "Multi-Hit",
    Special: "Bulb Recharge, Shot Bounces",
    Usage: null,
    Family: "Appease-mint",
};
const oGuacodile = {
    CodeName: "oGuacodile",
    EngName: "Guacodile",
    SunNum: 125,
    Attack: "Heavy",
    World: "Big Wave Beach",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Amphibious, Rush",
    Usage: null,
    Family: "Enforce-mint",
};
const oBananaLauncher = {
    CodeName: "oBananaLauncher",
    EngName: "Banana Launcher",
    SunNum: 500,
    Attack: "Massive",
    World: "Big Wave Beach",
    Recharge: "Fast",
    RangeArea: "Full Board, Tile",
    Special: "Firing Rate (Slow)",
    Usage: "Tap to Aim",
    Family: "Arma-mint",
};
const oMoonflower = {
    CodeName: "oMoonflower",
    EngName: "Moonflower",
    SunNum: 50,
    Attack: null,
    World: "Modern Day",
    Recharge: "Fast",
    RangeArea: null,
    Special: "Boost",
    Usage: "Sun (Variable)",
    Family: "Conceal-mint",
};
const oNightshade = {
    CodeName: "oNightshade",
    EngName: "Nightshade",
    SunNum: 75,
    Attack: "Heavy",
    World: "Modern Day",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: null,
    Usage: null,
    Family: "Conceal-mint",
};
const oShadowShroom = {
    CodeName: "oShadowShroom",
    EngName: "Shadow-shroom",
    SunNum: 50,
    Attack: "Moderate",
    World: "Modern Day",
    Recharge: "Mediocre",
    RangeArea: "Touch, Single",
    Special: "Poison",
    Usage: "Single, On Eaten",
    Family: "Conceal-mint",
};
const oDuskLobber = {
    CodeName: "oDuskLobber",
    EngName: "Dusk Lobber",
    SunNum: 150,
    Attack: "Moderate",
    World: "Modern Day",
    Recharge: "Mediocre",
    RangeArea: "Lobbed, 3x3",
    Special: null,
    Usage: null,
    Family: "Conceal-mint",
};
const oGrimrose = {
    CodeName: "oGrimrose",
    EngName: "Grimrose",
    SunNum: 75,
    Attack: "Huge",
    World: "Modern Day",
    Recharge: "Sluggish",
    RangeArea: "Lane",
    Special: "Zombies Dragged",
    Usage: "Single",
    Family: "Conceal-mint",
};