const oSnowPea = {
    CodeName: "oSnowPea",
    EngName: "Snow Pea",
    SunNum: 150,
    Attack: "Normal",
    World: "Premium",
    Recharge: "Mediocre",
    RangeArea: "Straight",
    Special: "Chill",
    Usage: "Single",
    Family: "Winter-mint",
};
const oPowerLily = {
    CodeName: "oPowerLily",
    EngName: "Power Lily",
    SunNum: 175,
    Attack: "Normal",
    World: "Premium",
    Recharge: "Very Slow",
    RangeArea: null,
    Special: null,
    Usage: "Single, Instant",
    Family: "Enchant-mint",
};
const oSquash = {
    CodeName: "oSquash",
    EngName: "Squash",
    SunNum: 50,
    Attack: "Massive",
    World: "Gemium",
    Recharge: "Sluggish",
    RangeArea: "Close",
    Special: "Zombies Smashed",
    Usage: "Single",
    Family: "Enforce-mint",
};
const oJalapeno = {
    CodeName: "oJalapeno",
    EngName: "Jalapeno",
    SunNum: 125,
    Attack: "Massive",
    World: "Gemium",
    Recharge: "Slow",
    RangeArea: "Lane",
    Special: null,
    Usage: "Single, Instant",
    Family: "Pepper-mint",
};
const oImitater = {
    CodeName: "oImitater",
    EngName: "Imitater",
    SunNum: "???",
    Attack: null,
    World: "Premium",
    Recharge: "???",
    RangeArea: null,
    Special: null,
    Usage: null,
    Family: "Enchant-mint",
};
const oHypnoShroom = {
    CodeName: "oHypnoShroom",
    EngName: "Hypno-shroom",
    SunNum: 125,
    Attack: null,
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Single",
    Special: null,
    Usage: "On Eaten",
    Family: "Enchant-mint",
};
const oPeaNut = {
    CodeName: "oPeaNut",
    EngName: "Pea-nut",
    SunNum: 150,
    Attack: "Normal",
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Straight",
    Special: null,
    Usage: "Wall (High)",
    Family: "Reinforce-mint",
};
const oChomper = {
    CodeName: "oChomper",
    EngName: "Chomper",
    SunNum: 150,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Close",
    Special: "Chew Speed",
    Usage: null,
    Family: "Enforce-mint",
};
const oHomingThistle = {
    CodeName: "oHomingThistle",
    EngName: "Homing Thistle",
    SunNum: 250,
    Attack: "Moderate",
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Full Board",
    Special: null,
    Usage: null,
    Family: "Spear-mint",
};
const oGhostPepper = {
    CodeName: "oGhostPepper",
    EngName: "Ghost Pepper",
    SunNum: 75,
    Attack: "Moderate",
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Close (Front & Back)",
    Special: null,
    Usage: null,
    Family: "Pepper-mint",
};
const oSweetPotato = {
    CodeName: "oSweetPotato",
    EngName: "Sweet Potato",
    SunNum: 150,
    Attack: null,
    World: "Gemium",
    Recharge: "Sluggish",
    RangeArea: "Multi-Lane (1x3)",
    Special: null,
    Usage: "Wall (High)",
    Family: "Reinforce-mint",
};
const oSapFling = {
    CodeName: "oSapFling",
    EngName: "Sap-fling",
    SunNum: 75,
    Attack: null,
    World: "Gemium",
    Recharge: "Fast",
    RangeArea: "Lobbed",
    Special: "Firing Rate (Mediocre), Stall",
    Usage: null,
    Family: "Contain-mint",
};
const oHurrikale = {
    CodeName: "oHurrikale",
    EngName: "Hurrikale",
    SunNum: 100,
    Attack: null,
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Lane",
    Special: "Chill",
    Usage: "Single, Instant",
    Family: "Contain-mint",
};
const oFirePeashooter = {
    CodeName: "oFirePeashooter",
    EngName: "Fire Peashooter",
    SunNum: 175,
    Attack: "Moderate",
    World: "Gemium",
    Recharge: "Fast",
    RangeArea: "Straight",
    Special: "Warming",
    Usage: null,
    Family: "Pepper-mint",
};
const oLavaGuava = {
    CodeName: "oLavaGuava",
    EngName: "Lava Guava",
    SunNum: 75,
    Attack: "Heavy",
    World: "Gemium",
    Recharge: "Mediocre",
    RangeArea: "Touch",
    Special: "Warming",
    Usage: "Single, Instant",
    Family: "Pepper-mint",
};
const oToadstool = {
    CodeName: "oToadstool",
    EngName: "Toadstool",
    SunNum: 200,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Close",
    Special: "Chew Speed",
    Usage: "Sun (Variable)",
    Family: "Enlighten-mint",
};
const oStrawburst = {
    CodeName: "oStrawburst",
    EngName: "Strawburst",
    SunNum: 400,
    Attack: "Variable",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Lobbed, 3x3",
    Special: "Growth",
    Usage: "Tap to Use",
    Family: "Bombard-mint",
};
const oCactus = {
    CodeName: "oCactus",
    EngName: "Cactus",
    SunNum: 175,
    Attack: "Normal",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Multi-Hit",
    Special: "Spike Damage",
    Usage: null,
    Family: "Spear-mint",
};
const oElectricBlueberry = {
    CodeName: "oElectricBlueberry",
    EngName: "Electric Blueberry",
    SunNum: 150,
    Attack: "Massive",
    World: "Premium",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Target Stronger Zombie",
    Usage: null,
    Family: "Fila-mint",
};
const oJackOLantern = {
    CodeName: "oJackOLantern",
    EngName: "Jack O' Lantern",
    SunNum: 225,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Sluggish",
    RangeArea: "3 Tiles",
    Special: null,
    Usage: null,
    Family: "Pepper-mint",
};
const oGrapeshot = {
    CodeName: "oGrapeshot",
    EngName: "Grapeshot",
    SunNum: 150,
    Attack: "Massive",
    World: "Premium",
    Recharge: "Slow",
    RangeArea: "3x3",
    Special: "Shot Bounces",
    Usage: "Single, Instant",
    Family: "Bombard-mint",
};
const oColdSnapdragon = {
    CodeName: "oColdSnapdragon",
    EngName: "Cold Snapdragon",
    SunNum: 150,
    Attack: "Moderate",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Close",
    Special: "Chill",
    Usage: null,
    Family: "Winter-mint",
};
const oShrinkingViolet = {
    CodeName: "oShrinkingViolet",
    EngName: "Shrinking Violet",
    SunNum: 50,
    Attack: null,
    World: "Premium",
    Recharge: "Sluggish",
    RangeArea: "3x3",
    Special: "Weaken Zombie",
    Usage: "Single, On Contact",
    Family: "Enchant-mint",
};
const oEscapeRoot = {
    CodeName: "oEscapeRoot",
    EngName: "Escape Root",
    SunNum: 50,
    Attack: "Massive",
    World: "Premium",
    Recharge: "Sluggish",
    RangeArea: "Touch",
    Special: "Arming Time (Mediocre)",
    Usage: "Tap to Swap",
    Family: "Bombard-mint",
};
const oGoldBloom = {
    CodeName: "oGoldBloom",
    EngName: "Gold Bloom",
    SunNum: 0,
    Attack: null,
    World: "Premium",
    Recharge: "Very Slow",
    RangeArea: null,
    Special: null,
    Usage: "Sun (Burst)",
    Family: "Enlighten-mint",
};
const oElectricCurrant = {
    CodeName: "oElectricCurrant",
    EngName: "Electric Currant",
    SunNum: 150,
    Attack: "Normal",
    World: "Premium",
    Recharge: "Mediocre",
    RangeArea: "Lane & Column",
    Special: null,
    Usage: null,
    Family: "Fila-mint",
};
const oWasabiWhip = {
    CodeName: "oWasabiWhip",
    EngName: "Wasabi Whip",
    SunNum: 150,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Close (Front & Back)",
    Special: "Warming",
    Usage: null,
    Family: "Enforce-mint",
};
const oKiwibeast = {
    CodeName: "oKiwibeast",
    EngName: "Kiwibeast",
    SunNum: 175,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Tile, 3x3, 5x5",
    Special: "Growth",
    Usage: null,
    Family: "Enforce-mint",
};
const oAppleMortar = {
    CodeName: "oAppleMortar",
    EngName: "Apple Mortar",
    SunNum: 175,
    Attack: "Moderate",
    World: "Premium",
    Recharge: "Mediocre",
    RangeArea: "Multi-Lane",
    Special: "Stun",
    Usage: null,
    Family: "Arma-mint",
};
const oWitchHazel = {
    CodeName: "oWitchHazel",
    EngName: "Witch Hazel",
    SunNum: 200,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Sluggish",
    RangeArea: "Full Board",
    Special: "Transform Zombie",
    Usage: null,
    Family: "Enchant-mint",
};
const oParsnip = {
    CodeName: "oParsnip",
    EngName: "Parsnip",
    SunNum: 150,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Close",
    Special: "Rush",
    Usage: null,
    Family: "Enforce-mint",
};
const oMissileToe = {
    CodeName: "oMissileToe",
    EngName: "Missile Toe",
    SunNum: 500,
    Attack: "Heavy",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Tile",
    Special: "Chill, Firing Rate (Slow)",
    Usage: "Tap to Aim",
    Family: "Winter-mint",
};
const oCaulipower = {
    CodeName: "oCaulipower",
    EngName: "Caulipower",
    SunNum: 250,
    Attack: null,
    World: "Premium",
    Recharge: "Very Slow",
    RangeArea: "Full Board",
    Special: "Target Stronger Zombie",
    Usage: null,
    Family: "Enchant-mint",
};
const oElectricPeashooter = {
    CodeName: "oElectricPeashooter",
    EngName: "Electric Peashooter",
    SunNum: 200,
    Attack: "Moderate",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Multi-Hit",
    Special: "Zombies Zapped",
    Usage: null,
    Family: "Fila-mint",
};
const oHollyBarrier = {
    CodeName: "oHollyBarrier",
    EngName: "Holly Barrier",
    SunNum: 150,
    Attack: "Normal",
    World: "Premium",
    Recharge: "Fast",
    RangeArea: "Touch, 3x3",
    Special: "Knockback, Barrier",
    Usage: "Tap to Aim, Wall (Elevated)",
    Family: "Reinforce-mint",
};